# Generated by Django 5.0.7 on 2024-08-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Management', '0003_profile_email_profile_profile_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='room_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
