# Generated by Django 5.0.7 on 2024-08-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_capturedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
