# Generated by Django 5.0.7 on 2024-08-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('Room', 'Room'), ('Amenity', 'Amenity'), ('Service', 'Service'), ('Other', 'Other')], max_length=50)),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
