# Generated by Django 5.0.7 on 2024-08-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Management', '0002_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='facility_type',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
