# Generated by Django 5.0.7 on 2024-08-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Management', '0003_remove_facility_facility_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('gym', 'Gym'), ('pool', 'Swimming Pool'), ('wifi', 'WiFi'), ('laundry', 'Laundry'), ('parking', 'Parking'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_image',
            field=models.ImageField(blank=True, null=True, upload_to='facility_images/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
